apiVersion: v1
kind: Service
metadata:
  name: counselgpt-embeddings
  labels:
    app: embeddings
spec:
  type: ClusterIP
  selector:
    app: embeddings
  ports:
  - name: http
    port: 8000
    targetPort: 8000

