apiVersion: v1
kind: Service
metadata:
  name: counselgpt-embeddings-mthiruma
  namespace: cse239fall2025
spec:
  selector:
    app: embeddings-counselgpt-mthiruma
  ports:
  - name: http
    port: 8000
    targetPort: 8000
