apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counselgpt-api-ingress
  namespace: cse239fall2025
spec:
  ingressClassName: haproxy
  rules:
  - host: counselgpt-mathesh.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: counselgpt-api-mthiruma
            port:
              number: 8000
  tls:
  - hosts:
    - counselgpt-mathesh.nrp-nautilus.io
