apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cse239fall2025
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s

    scrape_configs:
      # -------------------------------------------------------
      # 1) Prometheus self-monitoring
      # -------------------------------------------------------
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      # -------------------------------------------------------
      # 2) Nginx-thrift frontend
      # -------------------------------------------------------
      - job_name: 'nginx-frontend'
        metrics_path: /metrics
        static_configs:
        - targets:
          - 'nginx-thrift.cse239fall2025.svc.cluster.local:9091'
          labels:
            service: 'nginx-thrift'
            namespace: 'cse239fall2025'
        scrape_interval: 10s

      # -------------------------------------------------------
      # 3) Pushgateway metrics
      # -------------------------------------------------------
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
        - targets:
          - 'pushgateway.cse239fall2025.svc.cluster.local:9091'
          labels:
            namespace: 'cse239fall2025'
        scrape_interval: 10s

      # -------------------------------------------------------
      # 4) CounselGPT API - Please Dont remove or Override it whoever is editing add extra entry down
      # -------------------------------------------------------
      - job_name: 'counselgpt-api'
        metrics_path: /metrics
        static_configs:
        - targets:
          - 'counselgpt-api-mthiruma.cse239fall2025.svc.cluster.local:8000'
        scrape_interval: 10s

      # -------------------------------------------------------
      # 5) Redis Exporter metrics - Please Dont remove or Override it whoever is editing add extra entry down
      # -------------------------------------------------------
      - job_name: 'counselgpt-redis'
        metrics_path: /metrics
        static_configs:
        - targets:
          - 'counselgpt-redis-mthiruma.cse239fall2025.svc.cluster.local:9121'
        scrape_interval: 10s

      # -------------------------------------------------------
      # 6) DCGM GPU Metrics
      # -------------------------------------------------------
      - job_name: 'dcgm-exporter'
        metrics_path: /metrics
        static_configs:
        - targets:
          - 'dcgm-exporter.cse239fall2025.svc.cluster.local:9400'
        scrape_interval: 10s

