apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: counselgpt-api-monitor-mthiruma
  namespace: cse239fall2025
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: counselgpt-api-mthiruma
  namespaceSelector:
    matchNames:
    - cse239fall2025
  endpoints:
  - port: http
    interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor-mthiruma
  namespace: cse239fall2025
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis-mthiruma
  namespaceSelector:
    matchNames:
    - cse239fall2025
  endpoints:
  - port: metrics
    interval: 10s
