apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: counselgpt-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: counselgpt-api-mthiruma
  namespaceSelector:
    matchNames:
      - cse239fall2025
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
