apiVersion: v1
kind: Service
metadata:
  name: counselgpt-redis-mthiruma
  namespace: cse239fall2025
spec:
  selector:
    app: counselgpt-redis-mthiruma
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: embeddings
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9121
    targetPort: 9121
