apiVersion: v1
kind: Service
metadata:
  name: counselgpt-redis-mthiruma
  namespace: cse239fall2025
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: counselgpt-redis-mthiruma
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  # - name: redis
  #   port: 6379
  #   targetPort: 6379

  # - name: embeddings
  #   port: 8000
  #   targetPort: 8000

  # - name: metrics   # Redis Exporter
  #   port: 9121
  #   targetPort: 9121
