apiVersion: v1
kind: Service
metadata:
  name: counselgpt-redis
  labels:
    app: semantic-cache
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: semantic-cache
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: embeddings
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9121
    targetPort: 9121

