apiVersion: v1
kind: PersistentVolume
metadata:
  name: counselgpt-pv
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.69.137.58
    path: /models
  mountOptions:
    - hard
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counselgpt
  labels:
    app: counselgpt-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  volumeName: counselgpt-pv
  resources:
    requests:
      storage: 1024Gi