global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "counselgpt"
    static_configs:
      - targets: ["counselgpt-api:8000"]
        
  - job_name: "gpu"
    static_configs:
      - targets: ["dcgm:9400"]
        
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]