apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counselgpt-api-hpa
  labels:
    app: counselgpt-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counselgpt-api

  minReplicas: 1
  maxReplicas: 1 # TODO :- need atleast 3, I cant get a way around quotos now, but if it works it would be great

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60   # target 60% CPU usage
